  version: "3.7"
  services:
    rabbitmq3:
      image: rabbitmq:3-management
      container_name: rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ./db-data:/var/lib/rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=123456



