package calculatorProject;

import java.io.Serializable;
import java.math.BigDecimal;

//Class that is used to send/receive MSG via RABBITMQ
//Must implement Serializable interface to work with RABBITMQ desarialization process
//NB: This class is unique to the both modules, the jar is generated by maven and each module has to import it to have access
public class CalculatorData implements Serializable {
    public BigDecimal a;
    public BigDecimal b;
    public BigDecimal result;
    public int operation;


    public CalculatorData(BigDecimal a, BigDecimal b, int operation) {
        this.a = a;
        this.b = b;
        this.operation = operation;
    }

    public CalculatorData(BigDecimal a, BigDecimal b, BigDecimal result) {
        this.a = a;
        this.b = b;
        this.result = result;
    }
}
